using System;

namespace PHIDDO.MTX.LecacyDataExtract.Models.Models
{
    public class Record
    {
        public int public_health_case_uid { get; set; }
        public int Patient_UID { get; set; }
        public DateTime ReportedToStateDT { get; set; }
        public string JurisdictionCD_desc { get; set; }
        public string CaseCountyCD_Desc { get; set; }
        public string OutbreakCD_Desc { get; set; }
        public string MMWRWeekTX { get; set; }
        public string MMWRYearTX { get; set; }
        public string ClassificationCD_Desc { get; set; }
        public string EventDateTypeCD_Desc { get; set; }
        public DateTime EventDT { get; set; }
        public int SourceCase_UID { get; set; }
        public string InvestigationStatusCD_Desc { get; set; }
        public string CountyEpiNameTX { get; set; }
        public string PatientFirstNameTX { get; set; }
        public string PatientLastNameTX { get; set; }
        public string PatientNameSuffixTX { get; set; }
        public DateTime PatientDOB_DT { get; set; }
        public int PatientAgeNM { get; set; }
        public string PatientAgeTypeCD { get; set; }
        public string PatientAddressTX { get; set; }
        public string PatientCityTX { get; set; }
        public string PatientStateCD_Desc { get; set; }
        public string PatientZipCodeTX { get; set; }
        public string PatientCountyCD_Desc { get; set; }
        public string PatientPH { get; set; }
        public string PatientEthnicGroupCD_Desc { get; set; }
        public string PatientDeceasedCD { get; set; }
        public string PatientDiedFromDiseaseCD { get; set; }
        public DateTime PatientDeceasedDT { get; set; }
        public string PatientGenderCD { get; set; }
        public DateTime SxOnsetDT { get; set; }
        public string SxAbdominalPainCD_Desc { get; set; }
        public string SxAnorexiaCD_Desc { get; set; }
        public string SxChestPainCD_Desc { get; set; }
        public string SxChillsCD_Desc { get; set; }
        public string SxConjunctivitisCD_Desc { get; set; }
        public string SxCoughCD_Desc { get; set; }
        public string SxCoughNonprodCD_Desc { get; set; }
        public string SxDiarrheaCD_Desc { get; set; }
        public string SxSxsConsistentWithDieaseCD_Desc { get; set; }
        public string SxFeverCD_Desc { get; set; }
        public string SxHeadacheCD_Desc { get; set; }
        public string SxMyalgiaCD_Desc { get; set; }
        public string SxNauseaCD_Desc { get; set; }
        public string SxOthSxsTX { get; set; }
        public string SxCSRashCD_Desc { get; set; }
        public string SxRhinorrheaCD_Desc { get; set; }
        public string SxSeizuresCD_Desc { get; set; }
        public string sxSOBCD_Desc { get; set; }
        public string SxSoreThroatCD_Desc { get; set; }
        public string SxWeezingCD_Desc { get; set; }
        public string HRActivityTypeCD_Desc { get; set; }
        public DateTime HRStartDT { get; set; }
        public DateTime HREndDT { get; set; }
        public string HRAddressTX { get; set; }
        public string HRCityTX { get; set; }
        public string HRFacilityNameTX { get; set; }
        public string HRPhonePH { get; set; }
        public string HRStateCD_Desc { get; set; }
        public string RFSmokingHxCD_Desc { get; set; }
        public string CM_ARDS_CD_Desc { get; set; }
        public string CMChronicHeartOrCircDzCD_Desc { get; set; }
        public string CMChronicLiverDzCD_Desc { get; set; }
        public string CMchronicLungCD_Desc { get; set; }
        public string CMChronicRenalFailCD_Desc { get; set; }
        public string CMDiabetesCD_Desc { get; set; }
        public string CMDissemintravascularCoagCD_Desc { get; set; }
        public string CMOthImmSuppressCondCD_Desc { get; set; }
        public string CMVentilatorCD_Desc { get; set; }
        public string CMPneumoCD_Desc { get; set; }
        public DateTime HospAdmissionDT { get; set; }
        public DateTime HospTransferHospAdmissionDT { get; set; }
        public DateTime HospDischDT { get; set; }
        public DateTime HospTransferHospTransferDT { get; set; }
        public string HospForThisDzCD_Desc { get; set; }
        public string HospPatientHospitalizedCD_Desc { get; set; }
        public string HospPatientTransferdCD_Desc { get; set; }
        public string HospTransferHospNameCD_Desc { get; set; }
        public string HospNameCD_Desc { get; set; }
        public string SurvOthLabResSpecifyMethodTX { get; set; }
        public string SurvLabCD_Desc { get; set; }
        public DateTime SurvLabResultDT { get; set; }
        public string SurvMostPertSpecIsolatedCD_Desc { get; set; }
        public DateTime SurvSpecCollDT { get; set; }
        public string TxECMO_CD_Desc { get; set; }
        public string BridgedRaceCD_Desc { get; set; }
        public string HRSettingTypeCD_Desc { get; set; }
        public string CMPregCD_Desc { get; set; }
        public string VaccCovid_Desc { get; set; }
        public DateTime VaccCovidDose1Dt { get; set; }
        public string VaccCovidDose1Lot { get; set; }
        public string VaccCovidDose1ManfCD_Desc { get; set; }
        public DateTime VaccCovidDose2Dt { get; set; }
        public string VaccCovidDose2Lot { get; set; }
        public string VaccCovidDose2ManfCD_Desc { get; set; }
    }
}
